
services:
  # 1. Database Service
  postgres:
    image: postgres:15-alpine
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend Service
  server:
    build: ./server
    container_name: my_server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      PORT: 4000

  # 3. Frontend Service
  client:
    build: ./client
    container_name: my_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    # This environment variable is for the browser to know where the API is
    environment:
      REACT_APP_API_URL: http://localhost:4000
    depends_on:
      - server

volumes:
  postgres_data:
